apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edureka
  name: edureka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edureka
    template:
      metadata:
        labels:
          app: edureka
      spec:
        containers:
        - name: edureka
          image: 905418070139.dkr.ecr.ap-south-1.amazonaws.com/edureka:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8761
            name: http
            protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: edureka
    k8s-app: edureka
  name: edureka
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8761
  type: LoadBalancer
  selector:
    app: edureka
