apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app
  name: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
    template:
      metadata:
        labels:
          app: springboot-app
      spec:
        containers:
        - name: my-springboot-app
          image: 905418070139.dkr.ecr.ap-south-1.amazonaws.com/edureka:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8761
            name: http
            protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8761
  type: LoadBalancer
  selector:
    app: springboot-app  
